// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpizlvfvwazvpkuncxfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaXpsdmZ2d2F6dnBrdW5jeGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTM0MzEsImV4cCI6MjA3MTc2OTQzMX0.jOgObL_QINkmaz1jqpiOhx3HyU0Nooh8R1wSTkOTA3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});